steps:
  # Étape 1 : Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/img1', '.']
  
  # Étape 2 : Push de l'image Docker vers Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/img1']
  
  # Étape 3 : Déploiement sur Cloud Run Jobs
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'pa-scrapping-job'
      - '--image=gcr.io/$PROJECT_ID/img1'
      - '--region=europe-west9'
      - '--platform=managed'
      - '--execute-now'
      - '--allow-unauthenticated'
      - '--update-env-vars=GCP_PROJECT=$PROJECT_ID'
      - '--service-account=969372868884@cloudbuild.gserviceaccount.com'

# Paramètres généraux du Cloud Build
timeout: '1600s'
options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
