steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/scrapping_img', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/scrapping_img']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pa-scrapping-job'
      - '--image=gcr.io/$PROJECT_ID/scrapping_img'
      - '--platform=managed'
      - '--region=europe-west9'
      - '--allow-unauthenticated'
      - '--update-env-vars=GCP_PROJECT=$PROJECT_ID'

# Paramètres généraux du Cloud Build
timeout: '1600s'
options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
